name: Submitty CI-3

#perform a full vagrant up

on :
  push

jobs:
  full-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: Submitty
      - uses: actions/setup-python@v2
        with:
            python-version: '3.6'
      - name: Install Submitty
        run: |
          which python
          which pip
          which easy_install
          # sudo apt-get install python-setuptools
          # python3 -m pip install --upgrade pip
          # python3 -m pip install setuptools
          # sudo mkdir -p /usr/local/submitty/GIT_CHECKOUT/
          # sudo mv Submitty /usr/local/submitty/GIT_CHECKOUT/
          # cd /usr/local/submitty/GIT_CHECKOUT/Submitty
          # sudo bash ./.setup/install_system.sh
