name: Submitty CI-3

#perform a full vagrant up

on :
  push

jobs:
  full-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.6'
        with:
          path: Submitty
      - name: Install Submitty
        run: |
          sudo mkdir -p /usr/local/submitty/GIT_CHECKOUT/
          sudo mv Submitty /usr/local/submitty/GIT_CHECKOUT/
          cd /usr/local/submitty/GIT_CHECKOUT/Submitty
          sudo bash ./.setup/install_system.sh
