name: Submitty CI-2

on:
    push:

env:
  PGPASSWORD: submitty_dbuser
  PHP_USER: submitty_php
  PHP_GROUP: submitty_php
  CGI_USER: submitty_cgi
  SUBMITTY_DATA_DIR: /var/local/submitty
  SUBMITTY_INSTALL_DIR: /usr/local/submitty
  POSTGRES_HOST: localhost
  PHP_VER: 7.4

jobs:
    test-2:
      continue-on-error: true
      runs-on: ubuntu-latest
      steps:
        - name: foo
          run : |
            sudo useradd --home /tmp -c 'AUTH ONLY account' -M --shell /bin/false aphacker
            echo aphacker:aphacker | chpasswd
        - name: debug
          run : |
            cat /etc/pam.d/common-password
            

    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            path: SUBMITTY_CPY/
        - name: Copy Repo
          run: |
            # have to copy first, absolute paths not supported by actions/checkout@v2
              sudo mkdir -p ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
              sudo cp -R SUBMITTY_CPY/. ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
              sudo chmod -R go+rwx ${SUBMITTY_INSTALL_DIR}
              ln -s ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty/site /usr/local/submitty/site

        - uses: shivammathur/setup-php@2.7.0
          with:
            php-version: ${PHP_VER}
        - name: install
          run: |
            sudo apt-get update
            sudo apt install libseccomp-dev
            sudo apt install libboost-all-dev
            sudo apt install apache2
            sudo apt install apache2-suexec-custom
            sudo apt install libapache2-mod-authnz-external
            sudo apt install libapache2-mod-authz-unixgroup
            sudo apt install libapache2-mod-wsgi-py3
            sudo apt install nginx
            sudo apt install php${PHP_VER}-fpm
        - name: setup
          run: |
            sudo useradd -m submitty_cgi
            sudo useradd -m submitty_php
            cd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
            sudo a2enmod include rewrite actions cgi alias headers suexec authnz_external headers proxy_fcgi proxy_http proxy_wstunnel
            # cat /etc/php/$PHP_VER/fpm/php-fpm.conf
            sudo cp .setup/php-fpm/pool.d/submitty.conf /etc/php/$PHP_VER/fpm/pool.d/www.conf
            sudo rm -rf /etc/apache2/sites-available/*
            sudo rm -rf /etc/apache2/sites-enabled/*
            sudo cp -f .setup/apache/submitty.conf /etc/apache2/sites-available/submitty.conf
            sudo sed -e "s/Require host __your_domain__/Require all granted/g" --in-place /etc/apache2/sites-available/submitty.conf
            sudo cp .setup/apache/www-data /etc/apache2/suexec/www-data
            sudo chmod 0640 /etc/apache2/suexec/www-data
            sudo a2ensite submitty
            sudo service php${PHP_VER}-fpm start
            ls -lah /run/php/
            sudo bash -c 'echo "export PATH=$PATH" >> /etc/apache2/envvars'
            sudo apache2ctl -t
            sudo apachectl configtest
            sudo service php${PHP_VER}-fpm restart
            sudo service php${PHP_VER}-fpm restart
            sudo cat /var/log/php7.4-fpm.log
            sudo service apache2 restart
            sudo mkdir /etc/systemd/system/nginx.service.d
            sudo printf "[Service]\nExecStartPost=/bin/sleep 0.1\n" | sudo tee /etc/systemd/system/nginx.service.d/override.conf
            sudo rm -rf /etc/nginx/sites-available/*
            sudo rm -rf /etc/nginx/sites-enabled/*
            sudo cp -f .setup/nginx/submitty.conf /etc/nginx/sites-available/submitty.conf
            sudo chmod 644 /etc/nginx/sites-available/submitty.conf
            sudo ln -s /etc/nginx/sites-available/submitty.conf /etc/nginx/sites-enabled/submitty.conf
            sudo service nginx restart
        - name: composer
          run : |
            cd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty/site
            composer install --prefer-dist
        - name: curl
          run: |
            curl localhost
            ls -lah /var/log/apache2/
            echo "submitty"
            cat /var/log/apache2/submitty.log
            echo "error"
            cat /var/log/apache2/error.log
            echo "other_vhosts_access"
            cat /var/log/apache2/other_vhosts_access.log

    e2e:
        continue-on-error: true
        runs-on: ubuntu-latest
        services:
          postgres:
            image: postgres
            env: 
              POSTGRES_PASSWORD: submitty_dbuser
              POSTGRES_USER: postgres
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
              - 5432:5432

        steps:
          - uses: actions/checkout@v2
            with:
              path: SUBMITTY_CPY/
          - name: Copy Repo
            run: |
              # have to copy first, absolute paths not supported by actions/checkout@v2
                sudo mkdir -p ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
                sudo cp -R SUBMITTY_CPY/. ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
                sudo chmod -R go+rwx ${SUBMITTY_INSTALL_DIR}

          - uses: actions/setup-python@v2
            with:
              python-version: '3.6'
          - uses: shivammathur/setup-php@2.7.0
            with:
              extensions: imagick
              php-version: $PHP_VER
          - name: Cache Pip
            uses: actions/cache@v2
            with:
              path: path ~/.cache/pip
              key: ${{ runner.os }}-py-pip-${{ hashFiles('**/requirements.txt') }}
              restore-keys: |
                ${{ runner.os }}-py-pip
          - uses: nanasess/setup-chromedriver@master
          - name: Install Python dependencies
            run: |
              python3 -m pip install --upgrade pip setuptools wheel     
              pip3 install python-pam
              pip3 install sqlalchemy
              pip3 install selenium
              pip3 install tzlocal
              pip3 install jsonschema
              pip3 install jsonref
              pip3 install websocket_client
              pip3 install psycopg2 --user
              pip3 install docker
              pip3 install pyyaml
              pip3 install selenium
              pip3 install websocket_client
              pip3 install python-pam
              pip3 install python-dateutil
              pip3 install paramiko
              #needs to be globally available to daemon user created later
              sudo pip3 install docker
              sudo pip3 install paramiko
              sudo pip3 install tzlocal
              sudo pip3 install sqlalchemy
          - name: Get compose cache dir
            id: composer-cache
            run: |
              pushd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty/site
              echo "::set-output name=dir::$(composer config cache-files-dir)"
              popd
          - name: Install Composer Cache
            uses: actions/cache@v2
            with:
              path: ${{ steps.composer-cache.outputs.dir }}
              key: ${{ runner.os }}-php-composer-${{ hashFiles('**/composer.lock') }}
              restore-keys: |
                ${{ runner.os }}-php-composer-
          - name: Install PHP dependencies
            run: |
              pushd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty/site
              composer install --prefer-dist
              popd
          - name: Setup Submitty
            run: |
              PGPASSWORD=${PGPASSWORD} psql -d postgres -h localhost -U postgres -c "CREATE ROLE submitty_dbuser WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'submitty_dbuser'"
              PGPASSWORD=${PGPASSWORD} psql -d postgres -h localhost -U submitty_dbuser -c "CREATE DATABASE submitty"
              sudo apt-get update
              sudo apt install libseccomp-dev
              sudo apt install libboost-all-dev
              sudo apt install apache2
              sudo apt install apache2-suexec-custom
              sudo apt install libapache2-mod-authnz-external
              sudo apt install libapache2-mod-authz-unixgroup
              sudo apt install libapache2-mod-wsgi-py3
              sudo apt install nginx
              sudo apt install php${PHP_VER}-fpm
              export SUBMITTY_INSTALL_DIR=/usr/local/submitty #need to export otherwise shell scripts don't have access
              export SUBMITTY_REPOSITORY=${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
              pushd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
              sudo -E env "PATH=$PATH" bash .setup/testing/autograder.sh
              echo "before"
              cat /etc/pam.d/common-password
              sudo -E env "PATH=$PATH" bash .setup/testing/setup.sh
              echo "after"
              cat /etc/pam.d/common-password
              sudo cat /etc/pam.d/common-password 
              popd
          - name: Install Submitty Python Utils
            run: |
              export SUBMITTY_INSTALL_DIR=/usr/local/submitty 
              export SUBMITTY_REPOSITORY=${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
              pushd ${SUBMITTY_REPOSITORY}/python_submitty_utils
              sudo sed -i '12s/.*/Defaults env_keep += "PYTHONPATH"/' /etc/sudoers
              pip3 install . --user
              popd
          - name: Setup website
            run: |
              export SUBMITTY_INSTALL_DIR=/usr/local/submitty 
              export SUBMITTY_REPOSITORY=${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
              pushd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
              sudo -E env "PATH=$PATH" python3 /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/setup_sample_courses.py --no_submissions sample
              sudo -E env "PATH=$PATH" bash .setup/testing/setup_test_suite.sh
              sudo a2enmod include rewrite actions cgi alias headers suexec authnz_external headers proxy_fcgi proxy_http proxy_wstunnel
              sudo cp .setup/php-fpm/pool.d/submitty.conf /etc/php/$PHP_VER/fpm/php-fpm.conf
              sudo mkdir -p /run/php
              sudo chown www-data:www-data /run/php
              sudo chmod 755 /run/php
              sudo a2dissite 000-default
              sudo rm -rf /etc/apache2/sites-available/*
              sudo rm -rf /etc/apache2/sites-enabled/*
              sudo cp -f .setup/apache/submitty.conf /etc/apache2/sites-available/submitty.conf
              ls -lah /etc/apache2/sites-available
              sudo sed -e "s/Require host __your_domain__/Require all granted/g" --in-place /etc/apache2/sites-available/submitty.conf
              sudo cp .setup/apache/www-data /etc/apache2/suexec/www-data
              sudo chmod 0640 /etc/apache2/suexec/www-data
              sudo a2ensite submitty
              sudo bash -c 'echo "export PATH=$PATH" >> /etc/apache2/envvars'
              sudo apache2ctl -t
              sudo service php${PHP_VER}-fpm restart
              sudo service apache2 restart
              sudo mkdir /etc/systemd/system/nginx.service.d
              sudo printf "[Service]\nExecStartPost=/bin/sleep 0.1\n" | sudo tee /etc/systemd/system/nginx.service.d/override.conf
              sudo systemctl daemon-reload
              sudo rm -rf /etc/nginx/sites-available/*
              sudo rm -rf /etc/nginx/sites-enabled/*
              sudo cp -f .setup/nginx/submitty.conf /etc/nginx/sites-available/submitty.conf
              sudo chmod 644 /etc/nginx/sites-available/submitty.conf
              sudo ln -s /etc/nginx/sites-available/submitty.conf /etc/nginx/sites-enabled/submitty.conf
              sudo service nginx restart
          - name: Debug
            run: |
              curl http://localhost
          - name: Debug
            run : |
              ls -lah /var/log/apache2/
              cat /var/log/apache2/error.log
          - name: Debug2
            run : |
              ls -lah /var/log/nginx
              sudo cat /var/log/nginx/error.log
          - name: Debug3
            run : |
              ls -lah /var/log/
              sudo cat /var/log/php${PHP_VER}-fpm.log
          - name: Run tests
            run: |
              export SUBMITTY_INSTALL_DIR=/usr/local/submitty 
              export SUBMITTY_REPOSITORY=${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
              pushd ${SUBMITTY_REPOSITORY}
              echo "Authentication Method => $(sudo jq -r ".authentication_method" /usr/local/submitty/config/database.json)"
              TEST_URL="http://localhost" python3 -m unittest discover -v --start-directory tests
              sudo sed -ie "s/Pam/Database/g" /usr/local/submitty/config/database.json
              echo "Authentication Method => $(sudo jq -r ".authentication_method" /usr/local/submitty/config/database.json)"
              pushd tests
              TEST_URL="http://localhost" python3 -m unittest e2e.test_login
              popd
              SEMESTER=$(python3 -c 'from datetime import datetime; today = datetime.today(); semester = ("s" if today.month < 7 else "f") + str(today.year)[-2:]; print(semester)')
              sudo python3 /usr/local/submitty/bin/generate_repos.py ${SEMESTER} sample open_homework
              bash tests/git_test.sh
              sudo bash tests/test_site_error_log.sh



      
