name: Submitty CI-2

on:
    push:

env:
  PGPASSWORD: submitty_dbuser
  PHP_USER: submitty_php
  PHP_GROUP: submitty_php
  CGI_USER: submitty_cgi
  SUBMITTY_DATA_DIR: /var/local/submitty
  SUBMITTY_INSTALL_DIR: /usr/local/submitty
  POSTGRES_HOST: localhost

jobs:
    # test:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/checkout@v2
    #     - uses: actions/setup-python@v2
    #       with:
    #         python-version: '3.6'
    #     - name: Cache Pip
    #       uses: actions/cache@v2
    #       with:
    #         path: path ~/.cache/pip
    #         key: ${{ runner.os }}-py-pip-${{ hashFiles('**/requirements.txt') }}
    #         restore-keys: |
    #           ${{ runner.os }}-py-pip
    #     - name: Install Python dependencies
    #       run: |
    #         pip3 install --upgrade pip
    #         sudo pip3 install paramiko
    #     - name: test
    #       run: |
    #         adduser submitty_daemon --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
    #         sudo -H -u submitty_daemon python3 sbin/shipper_utils/systemctl_wrapper.py stop --target perform_on_all_workers

    e2e-local:
      runs-on: ubuntu-latest
      steps:
        - name : setup local db
          run: |
            sudo mkdir -p ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
            sudo apt update
            sudo apt-get install systemd
            sudo apt install postgresql postgresql-contrib
            sudo service postgresql  start
            sudo -u postgres psql -c "CREATE ROLE submitty_dbuser WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'submitty_dbuser'"
            PGPASSWORD=${PGPASSWORD} psql -d postgres -h localhost -U submitty_dbuser -c "CREATE DATABASE submitty"
        - uses: actions/checkout@v2
          with:
            path: SUBMITTY_CPY/
        - name: TEST
          run: |
            # have to copy firsdt, absolute paths not supported by actions/checkout@v2
              cp -r SUBMITTY_CPY/. ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty

        - uses: actions/setup-python@v2
          with:
            python-version: '3.6'
        - uses: shivammathur/setup-php@2.7.0
          with:
            extensions: imagick
        - name: Cache Pip
          uses: actions/cache@v2
          with:
            path: path ~/.cache/pip
            key: ${{ runner.os }}-py-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-py-pip
        - name: Install Python dependencies
          run: |
            pip3 install --upgrade pip
            pip3 install python-pam
            pip3 install sqlalchemy
            pip3 install selenium
            pip3 install tzlocal
            pip3 install jsonschema
            pip3 install jsonref
            pip3 install docker
            pip3 install websocket_client
            pip3 install psycopg2
            #needs to be globally available to daemon user created later
            sudo pip3 install paramiko

        - name: Get compose cache dir
          id: composer-cache
          run: |
            pushd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty/site
            echo "::set-output name=dir::$(composer config cache-files-dir)"
            popd
        - name: Install Composer Cache
          uses: actions/cache@v2
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-php-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-php-composer-
        - name: Install PHP dependencies
          run: |
            pushd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty/site
            composer install --prefer-dist
            popd
        - name: Setup Submitty
          run: |
            sudo apt install libseccomp-dev
            sudo apt install libboost-all-dev
            export SUBMITTY_INSTALL_DIR=/usr/local/submitty #need to export otherwise shell scripts don't have access
            export SUBMITTY_REPOSITORY=${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
            pushd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
            ls -la $SUBMITTY_INSTALL_DIR/GIT_CHECKOUT/Submitty/.setup
            sudo -E env "PATH=$PATH" bash .setup/testing/autograder.sh
            ls -la $SUBMITTY_INSTALL_DIR/GIT_CHECKOUT/Submitty/.setup
            sudo ln -s $(pwd) /usr/local/submitty
            ls -la $SUBMITTY_INSTALL_DIR
            sudo -E env "PATH=$PATH" bash .setup/testing/setup.sh


    e2e:
        runs-on: ubuntu-latest
        services:
          postgres:
            image: postgres
            env: 
              POSTGRES_PASSWORD: submitty_dbuser
              POSTGRES_USER: submitty_dbuser
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
              - 5432:5432

        steps:
          - uses: actions/checkout@v2
            with:
              path: SUBMITTY_CPY/
          - name: Copy Repo
            run: |
              # have to copy first, absolute paths not supported by actions/checkout@v2
                sudo mkdir -p ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
                sudo cp -R SUBMITTY_CPY/. ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
                chmod -R og=rw ${SUBMITTY_INSTALL_DIR}
          - uses: actions/setup-python@v2
            with:
              python-version: '3.6'
          - uses: shivammathur/setup-php@2.7.0
            with:
              extensions: imagick
          - name: Cache Pip
            uses: actions/cache@v2
            with:
              path: path ~/.cache/pip
              key: ${{ runner.os }}-py-pip-${{ hashFiles('**/requirements.txt') }}
              restore-keys: |
                ${{ runner.os }}-py-pip
          - name: Install Python dependencies
            run: |
              pip3 install --upgrade pip
              pip3 install python-pam
              pip3 install sqlalchemy
              pip3 install selenium
              pip3 install tzlocal
              pip3 install jsonschema
              pip3 install jsonref
              pip3 install docker
              pip3 install websocket_client
              pip3 install psycopg2
              #needs to be globally available to daemon user created later
              sudo pip3 install paramiko
          - name: Get compose cache dir
            id: composer-cache
            run: |
              pushd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty/site
              echo "::set-output name=dir::$(composer config cache-files-dir)"
              popd
          - name: Install Composer Cache
            uses: actions/cache@v2
            with:
              path: ${{ steps.composer-cache.outputs.dir }}
              key: ${{ runner.os }}-php-composer-${{ hashFiles('**/composer.lock') }}
              restore-keys: |
                ${{ runner.os }}-php-composer-
          - name: Install PHP dependencies
            run: |
              pushd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty/site
              composer install --prefer-dist
              popd
          - name: Setup Submitty
            run: |
              PGPASSWORD=${PGPASSWORD} psql -d postgres -h localhost -U submitty_dbuser -c "CREATE DATABASE submitty"
              sudo apt install libseccomp-dev
              sudo apt install libboost-all-dev
              export SUBMITTY_REPOSITORY=$(pwd)/GIT_CHECKOUT/Submitty
              export SUBMITTY_INSTALL_DIR=$(pwd)
              echo $SUBMITTY_INSTALL_DIR
              pushd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty/
              sudo -E env "PATH=$PATH" bash .setup/testing/autograder.sh
              sudo ln -s $(pwd) /usr/local/submitty
              ls -la $SUBMITTY_INSTALL_DIR
              sudo -E env "PATH=$PATH" bash .setup/testing/setup.sh



  